### PR TITLE
Force EHentai to use the Minimal display mode

### LINKED ISSUE #25: Fix E* Cookies (Display, etc.)
Opening this so it can be tracked

### PR DESCRIPTION
**Pull request by ilwaz**
Closes #25

CC: @Scrxtchy

### CODE REVIEW

**Comment by Scrxtchy** [comment]
I might also just test this myself

**Comment by Scrxtchy** [comment]
Hmm, it only appears it will apply to ExH when you login. In the process when it creates the settings profile

If any existing logins exist, they may be using the old profile.
Can be fixed manually by either, logging out and back in. Or

**Comment by ilwaz** [comment]
It'll actually re-upload the settings on app update: https://github.com/ilwaz/TachiyomiEH/blob/master/app/src/main/java/eu/kanade/tachiyomi/ui/main/MainActivity.kt#L203.

And the change in EHentai.kt should fix this for non-logged in users.

**Comment by ilwaz** [comment]
Jk, the `eh_showSettingsUploadWarning` preference is set to false after the first login

**Comment by Scrxtchy** [comment]
>  How do you feel about just uploading a new profile every fresh app startup?

This appears to take some time for some reason, I do not think it very wise to do so

**Comment by Scrxtchy** [comment]
Opened #28 as an option

**Comment by Scrxtchy** [comment]
The only thing left is we need to really warn existing users about this

Anyone downloading the app to upgrade for NN9's won't have to worry about it though

**Comment by ilwaz** [comment]
Yep, we can call it out in the changelog and then tell any users who are experiencing errors to do it in open issues.

**Pull request merged**
